name: Build and deploy JAR app to Azure Web App - golangapp88

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'microsoft'

      # Add step to list directory contents to identify where pom.xml is located
      - name: List directory contents at root
        run: ls -la

      - name: List contents of all subdirectories
        run: find . -type d -exec ls -la {} \;

      # Build with Maven (remove working-directory if pom.xml is in root)
      - name: Build with Maven
        run: mvn clean install
        #working-directory: ./path/to/your/project  # Uncomment and update only if needed

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EDE04C60052C4C208A88754AAA54559C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3260BA288C25449DA047170AD472EEB4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_CC0E74565EB8436E8F4872D69E3E5BB1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'golangapp88'
          slot-name: 'Production'
          package: '*.jar'
